### ISSUE TITLE
Mcrypt Extension

### ISSUE THREAD

**Issue by hykrit** [anonymous33rus/wowlegions_blc#1]
<img width="933" alt="skarmklipp" src="https://user-images.githubusercontent.com/43646907/46160710-b9e38480-c283-11e8-9c92-0c28a41b5de1.PNG">
I am unable to enable the Mcrypt extension! Do I need to downgrade my php version maybe? 
Thank you!

**Comment by anonymous33rus** [comment]
Ignore this message, try to install the site. I do not setup a web server.
